# TODO: implement doc linting
[tox]
envlist = py{38,39,310,311,312,313,314}-lint, py38-lintreadme, py{38,39,310,311,312,313,314}-mypy, py{38,39,310,311,312,313,314}-test
source_dir = pydantictes
test_dir = test

[gh-actions]
python =
    3.8: py38-mypy, py38-lint, py38-test, py38-lintreadme
    3.9: py39-mypy, py39-lint, py39-test
    3.10: py310-mypy, py310-lint, py310-test
    3.11: py311-mypy, py311-lint, py311-test
    3.12: py312-mypy, py312-lint, py312-test
    3.13: py313-mypy, py313-lint, py313-test
    3.14: py314-mypy, py314-lint, py314-test

[testenv]
commands =
    test: pytest -s {[tox]test_dir} {posargs}
    lint: flake8 {[tox]source_dir} {[tox]test_dir} {posargs}
    lintreadme: make lint-readme
    mypy: mypy {[tox]source_dir} {[tox]test_dir} {posargs}
deps =
    lint: flake8-import-order
    lint: flake8-bugbear
    lint: flake8
    mypy: mypy
    mypy: types-requests
    mypy: pytest
    test: pytest
    test: -rrequirements.txt
    lintreadme: readme
skip_install =
    lint,lintreadme: True
allowlist_externals =
    lintreadme: make
passenv =
    FUNNEL_*
    GO*
    GIT*
    HOME
